[package]
name = "bathpack"
version = "0.1.0"
authors = ["SÃ¸ren Mortensen <soren@sorenmortensen.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.4"
